### ISSUE TITLE
Add 'topics' to this repo

### ISSUE THREAD

**Issue by amitdo** [tmbarchive/ocropy#182]
https://github.com/blog/2309-introducing-topics

**Comment by amitdo** [comment]
Suggested topics:

* ocr
* lstm
* machine-learning
* ocropy
* ocropus
* python

**Comment by zuphilip** [comment]
Yes, that is a good idea. Suggested topics looks good for me, additionally one can also add
* hocr
* binarization
* page-segmentation

This can only been done by @tmbdev .

**Comment by amitdo** [comment]
Are you sure you can't do it yourself?

**Comment by stweil** [comment]
I'm co-maintainer for the [hocr-tools](https://github.com/tmbdev/hocr-tools) and cannot add topics there, so I think Philipp is in a similar situation here. Obviously only the project owner can add topics.

**Comment by stweil** [comment]
@tmbdev, perhaps you can assign Philipp as "co-owner", so he gets the rights needed for setting the topics?
